brew install nvim
brew install kubectl 
brew install httpie 
brew install exa 
brew install bat 
brew install entr 
brew install chruby 
brew install codium 
brew install grip 
brew install diff-so-fancy 
brew install cloc 
brew install jq 
brew install live-server 
